name: Rollback

on:
    # 手动触发回滚
    workflow_dispatch:
        inputs:
            rollback_version:
                description: '回滚版本 (时间_简短commit id)'
                required: false
                default: ''

env:
    NODE_VERSION: 'lts/*'
    DEPLOY_PATH: '/var/www/html'
    APP_NAME: 'frontend-app'

jobs:
    rollback:
        if: github.event.inputs.rollback_version != ''
        runs-on: ubuntu-latest

        steps:
            - name: 执行回滚
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      cd ${{ env.DEPLOY_PATH }}
                      if [ -f "${{ env.APP_NAME }}_${{ github.event.inputs.rollback_version }}.backup.tar.gz" ]; then
                        rm -rf ${{ env.APP_NAME }}/dist
                        mkdir -p ${{ env.APP_NAME }}/dist
                        tar -xzf "${{ env.APP_NAME }}_${{ github.event.inputs.rollback_version }}.backup.tar.gz" -C "${{ env.APP_NAME }}/dist" --strip-components 1
                        echo "回滚成功"
                      else
                        echo "回滚版本不存在: ${{ env.APP_NAME }}_${{ github.event.inputs.rollback_version }}.backup.tar.gz"
                        echo "可用备份文件:"
                        ls -lat | grep "\.backup\.tar\.gz" | sort || echo "无备份文件"
                        exit 1
                      fi
